name: numattendance
description: Num Attendance Tracking with IOT Device.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1

  firebase_core: ^3.12.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  firebase_messaging: ^15.2.4

  dropdown_button2: ^2.3.9
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
